version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_builder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resume -d resume_builder"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "ssl=off"]

volumes:
  postgres_data:
