/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ForgotPassword: typeof import('./src/components/ForgotPassword.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    PaymentDialog: typeof import('./src/components/PaymentDialog.vue')['default']
    ProfileForm: typeof import('./src/components/ProfileForm.vue')['default']
    ResetPassword: typeof import('./src/components/ResetPassword.vue')['default']
    ResumeBuilder: typeof import('./src/components/ResumeBuilder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./src/components/SignupForm.vue')['default']
  }
}
