services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_builder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resume -d resume_builder"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_builder

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
