services:
  # db:
  #   container_name: db
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: resume
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: resume_builder
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U resume -d resume_builder"]
  #     interval: 1s
  #     timeout: 1s
  #     retries: 3

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 3
      
  backend:
    # container_name: backend
    build: ./backend
    # ports:
    #   - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_builder
    env_file:
      - ./backend/.env
    volumes:
      - uploads_data:/app/uploads
      - output_data:/app/app/output
      - ./backend/alembic:/app/alembic
      - ./backend/app/latex/templates:/app/app/latex/templates
      - ./backend/app/latex/templates.json:/app/app/latex/templates.json
    deploy:
      replicas: 3

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  proxy:
    container_name: proxy
    build: ./nginx
    ports:
     - "80:80"
    depends_on:
      - frontend
      - backend
      - redis
    restart: always


volumes:
  uploads_data:
  output_data:
