"""remove job description from resume

Revision ID: 2703ef06f694
Revises: 3ad1e5d76fe1
Create Date: 2025-08-24 18:27:19.733654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2703ef06f694'
down_revision: Union[str, None] = '3ad1e5d76fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'job_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
