"""add summary and analysis s3 keys to resume

Revision ID: 3ad1e5d76fe1
Revises: 878823199130
Create Date: 2025-08-24 18:17:10.882111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad1e5d76fe1'
down_revision: Union[str, None] = '878823199130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('summary_s3_key', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('detailed_analysis_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'detailed_analysis_s3_key')
    op.drop_column('resumes', 'summary_s3_key')
    # ### end Alembic commands ###
