"""Remove resume_path from Profile model

Revision ID: 5446d2f51222
Revises: cascade_delete_user_cleanup
Create Date: 2025-08-22 09:59:06.864382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5446d2f51222'
down_revision: Union[str, None] = 'cascade_delete_user_cleanup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'resume_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('resume_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
