"""Add latex_templates table

Revision ID: 6cfd87d62e1c
Revises: 2703ef06f694
Create Date: 2025-08-25 10:28:53.703248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfd87d62e1c'
down_revision: Union[str, None] = '2703ef06f694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latex_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False), # tex file S3 key
    sa.Column('image_path', sa.String(), nullable=True), # image file S3 key
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('single_page', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_latex_templates_id'), 'latex_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latex_templates_id'), table_name='latex_templates')
    op.drop_table('latex_templates')
    # ### end Alembic commands ###
