"""add company job title to resume

Revision ID: 878823199130
Revises: d1fcae261e55
Create Date: 2025-08-24 17:41:12.421366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878823199130'
down_revision: Union[str, None] = 'd1fcae261e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('educations_profile_id_fkey', 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint('projects_profile_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint('publications_profile_id_fkey', 'publications', type_='foreignkey')
    op.create_foreign_key(None, 'publications', 'profiles', ['profile_id'], ['id'])
    op.add_column('resumes', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('job_description_s3_key', sa.String(), nullable=True))
    op.drop_constraint('skills_profile_id_fkey', 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint('volunteer_works_profile_id_fkey', 'volunteer_works', type_='foreignkey')
    op.create_foreign_key(None, 'volunteer_works', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint('work_experiences_profile_id_fkey', 'work_experiences', type_='foreignkey')
    op.create_foreign_key(None, 'work_experiences', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_experiences', type_='foreignkey')
    op.create_foreign_key('work_experiences_profile_id_fkey', 'work_experiences', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'volunteer_works', type_='foreignkey')
    op.create_foreign_key('volunteer_works_profile_id_fkey', 'volunteer_works', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key('skills_profile_id_fkey', 'skills', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resumes', 'job_description_s3_key')
    op.drop_column('resumes', 'job_title')
    op.drop_column('resumes', 'company_name')
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.create_foreign_key('publications_profile_id_fkey', 'publications', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_profile_id_fkey', 'projects', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key('educations_profile_id_fkey', 'educations', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
