"""add use_resume_as_reference to profiles

Revision ID: add_use_resume_as_reference
Revises: add_resume_file_path
Create Date: 2025-01-08 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_use_resume_as_reference'
down_revision = '61d06c8400a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('use_resume_as_reference', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'use_resume_as_reference')
    # ### end Alembic commands ###
