"""add is_admin field to users table

Revision ID: b25524f4b2fd
Revises: fdaa2a243024
Create Date: 2025-07-30 20:25:49.023794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25524f4b2fd'
down_revision: Union[str, None] = 'fdaa2a243024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
