"""Add country to educations table

Revision ID: bbca5f148aae
Revises: c43d86d6f82e
Create Date: 2025-08-20 14:35:50.957967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbca5f148aae'
down_revision: Union[str, None] = 'c43d86d6f82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('educations', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('educations', 'location')
    op.add_column('projects', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('volunteer_works', sa.Column('country', sa.String(), nullable=True))
    op.add_column('volunteer_works', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('volunteer_works', 'location')
    op.add_column('work_experiences', sa.Column('country', sa.String(), nullable=True))
    op.add_column('work_experiences', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('work_experiences', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experiences', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('work_experiences', 'city')
    op.drop_column('work_experiences', 'country')
    op.add_column('volunteer_works', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('volunteer_works', 'city')
    op.drop_column('volunteer_works', 'country')
    op.drop_column('projects', 'industry')
    op.add_column('educations', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('educations', 'city')
    op.drop_column('educations', 'country')
    # ### end Alembic commands ###
