"""replace_github_url_with_industry_and_split_location

Revision ID: c43d86d6f82e
Revises: 47bb84739b84
Create Date: 2025-08-20 19:12:45.403892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43d86d6f82e'
down_revision: Union[str, None] = '47bb84739b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add industry column to profiles table
    op.add_column('profiles', sa.Column('industry', sa.String(), nullable=True))
    
    # Add country and city columns to profiles table
    op.add_column('profiles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    
    # Remove github_url from profiles table
    op.drop_column('profiles', 'github_url')
    
    # Remove location from profiles table
    op.drop_column('profiles', 'location')
    
    # Remove github_url from projects table
    op.drop_column('projects', 'github_url')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add github_url back to projects table
    op.add_column('projects', sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Add location back to profiles table
    op.add_column('profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Add github_url back to profiles table
    op.add_column('profiles', sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Remove city, country, and industry from profiles table
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'industry')
    
    # ### end Alembic commands ###
