"""add_definition_path_to_latex_template

Revision ID: f1702499ffea
Revises: 76d543973c13
Create Date: 2025-08-28 16:23:36.715800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1702499ffea'
down_revision: Union[str, None] = '76d543973c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latex_templates', sa.Column('definition_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('latex_templates', 'definition_path')
    # ### end Alembic commands ###
