"""rename content to content_s3_key in resumes table

Revision ID: fbcbd601f235
Revises: c43d86d6f82e
Create Date: 2025-08-21 22:27:03.153932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcbd601f235'
down_revision: Union[str, None] = 'c43d86d6f82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'content', new_column_name='content_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'content_s3_key', new_column_name='content')
    # ### end Alembic commands ###
