"""add_oauth_fields_to_users

Revision ID: fdaa2a243024
Revises: 800ad98a5b63
Create Date: 2025-07-30 17:44:55.927458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdaa2a243024'
down_revision: Union[str, None] = '800ad98a5b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###
