<template>
  <v-container class="terms-of-service-view" fluid style="background: linear-gradient(to top right, #E3F2FD, #BBDEFB);">
    <v-row justify="center">
      <v-col cols="12" lg="10" xl="8">
        <v-card 
          class="pa-md-8 pa-4" 
          elevation="12" 
          rounded="xl" 
          style="backdrop-filter: blur(10px); background-color: rgba(255, 255, 255, 0.9);"
        >
          <v-card-title class="text-h4 font-weight-bold mb-6 text-grey-darken-3 text-center">
            <v-icon icon="mdi-file-document-outline" class="mr-3" color="primary"></v-icon>
            Terms of Service
          </v-card-title>
          
          <v-card-text class="pa-0">
            <div class="markdown-content" v-html="formattedContent"></div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { marked } from 'marked'

const termsOfServiceContent = `# Terms of Service

**Last Updated:** August 15, 2025

## 1. Agreement to Terms

By accessing and using our AI-powered resume customization service (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.

## 2. Description of Service

Our Service provides an AI-powered platform that helps users create and customize resumes. The Service uses artificial intelligence to generate content suggestions, formatting options, and personalized resume elements based on user input.

## 3. AI-Generated Content Disclaimer

**IMPORTANT:** The resume content generated by our AI system may not be completely accurate to your actual experiences, skills, or qualifications. Key points regarding AI-generated content:

- AI-generated content is provided as a **guideline and suggestion only**, not as factual truth
- You are **solely responsible** for reviewing, editing, and verifying all AI-generated content
- You must ensure all information in your final resume accurately represents your experience and qualifications
- Our Service provides options to review and edit all AI-generated content before finalizing your resume
- **The AI-generated content should be used as a starting point and inspiration, not as definitive statements about your background**

## 4. User Responsibilities

By using our Service, you agree to:

- Provide accurate and truthful information about your background and experience
- Review and verify all AI-generated content before using it
- Edit and customize AI-generated content to accurately reflect your actual experience
- Use the Service in compliance with all applicable laws and regulations
- Not use the Service for any fraudulent or deceptive purposes

## 5. Limitation of Liability for Employment Outcomes

**EMPLOYMENT DISCLAIMER:** Our company is **NOT LIABLE** for:

- Interview rejections you may receive
- Job applications that are unsuccessful
- Employment termination or job loss
- Any negative employment outcomes or career setbacks
- Decisions made by employers, recruiters, or hiring managers

You acknowledge that:
- Employment decisions are made by employers based on multiple factors beyond resume content
- We do not guarantee job interviews, employment offers, or career success
- Your resume is just one component of the job application process
- Employment outcomes depend on factors including market conditions, competition, employer preferences, and your qualifications

## 6. Account Registration and Security

- You must provide accurate and complete information when creating an account
- You are responsible for maintaining the security of your account credentials
- You must notify us immediately of any unauthorized access to your account

## 7. Acceptable Use Policy

You may not use our Service to:
- Create false, misleading, or fraudulent resume content
- Violate any applicable laws or regulations
- Infringe on intellectual property rights of others
- Upload malicious software or harmful content
- Attempt to gain unauthorized access to our systems

## 8. Intellectual Property Rights

- You retain ownership of the content you provide to our Service
- We grant you a license to use the AI-generated content in your resumes
- Our Service, software, and technology remain our intellectual property
- You may not reverse engineer, copy, or distribute our software

## 9. Service Availability and Modifications

- We strive to maintain continuous service availability but do not guarantee uninterrupted access
- We reserve the right to modify, suspend, or discontinue the Service at any time
- We may update these Terms from time to time, and continued use constitutes acceptance

## 10. Disclaimers and Warranties

TO THE MAXIMUM EXTENT PERMITTED BY LAW:

- Our Service is provided "AS IS" and "AS AVAILABLE"
- We make no warranties regarding the accuracy, reliability, or completeness of AI-generated content
- We disclaim all warranties, express or implied, including merchantability and fitness for a particular purpose
- We do not warrant that the Service will be error-free or meet your specific requirements

## 11. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR LIABILITY IS LIMITED AS FOLLOWS:

- We shall not be liable for any indirect, incidental, special, or consequential damages
- Our total liability shall not exceed the amount you paid for our Service in the 12 months preceding the claim
- We are not liable for any damages resulting from your use or inability to use the Service
- This limitation applies regardless of the legal theory of liability

## 12. Indemnification

You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from:
- Your use of the Service
- Your violation of these Terms
- Content you provide to the Service
- Your employment-related activities or outcomes

## 13. Termination

- We may terminate your access to the Service at any time for violation of these Terms
- You may terminate your account at any time by contacting us
- Upon termination, your right to use the Service ceases immediately

## 14. Governing Law and Dispute Resolution

- These Terms shall be governed by the laws of [Your Jurisdiction]
- Any disputes shall be resolved through binding arbitration
- You agree to resolve disputes individually, not as part of a class action

## 15. Data Processing and Privacy

Your use of our Service is subject to our Privacy Policy, which is incorporated by reference into these Terms. Please review our Privacy Policy to understand how we collect, use, and protect your personal information.

## 16. Severability

If any provision of these Terms is deemed invalid or unenforceable, the remaining provisions shall remain in full force and effect.

## 17. Contact Information

If you have questions about these Terms, please contact us at:
- Email: [your-email@company.com]
- Address: [Your Company Address]

## 18. Entire Agreement

These Terms, together with our Privacy Policy and User Agreement, constitute the entire agreement between you and us regarding your use of the Service.

By using our Service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.`

const formattedContent = computed(() => {
  return marked(termsOfServiceContent, { breaks: true })
})
</script>

<style scoped>
.terms-of-service-view {
  min-height: 100vh;
  padding: 24px 0;
}

.markdown-content {
  background-color: white;
  padding: 32px;
  border-radius: 12px;
  border: 1px solid #e0e0e0;
  line-height: 1.8;
  font-size: 0.95rem;
  max-height: 80vh;
  overflow-y: auto;
}

/* Markdown styling */
.markdown-content :deep(h1) {
  color: #1976d2;
  font-size: 2.2rem;
  font-weight: 700;
  margin: 0 0 24px 0;
  padding-bottom: 12px;
  border-bottom: 3px solid #1976d2;
}

.markdown-content :deep(h2) {
  color: #1565c0;
  font-size: 1.6rem;
  font-weight: 600;
  margin: 32px 0 16px 0;
  padding-bottom: 8px;
  border-bottom: 2px solid #e3f2fd;
}

.markdown-content :deep(h3) {
  color: #1976d2;
  font-size: 1.3rem;
  font-weight: 600;
  margin: 24px 0 12px 0;
}

.markdown-content :deep(h4) {
  color: #424242;
  font-size: 1.1rem;
  font-weight: 600;
  margin: 20px 0 10px 0;
}

.markdown-content :deep(p) {
  margin: 12px 0;
  color: #424242;
  text-align: justify;
}

.markdown-content :deep(ul), 
.markdown-content :deep(ol) {
  margin: 16px 0;
  padding-left: 24px;
}

.markdown-content :deep(li) {
  margin: 8px 0;
  color: #424242;
}

.markdown-content :deep(strong) {
  color: #1976d2;
  font-weight: 600;
}

.markdown-content :deep(em) {
  color: #666;
  font-style: italic;
}

.markdown-content :deep(code) {
  background-color: #f5f5f5;
  padding: 2px 6px;
  border-radius: 4px;
  font-family: 'Courier New', monospace;
  font-size: 0.9em;
}

.markdown-content :deep(blockquote) {
  border-left: 4px solid #1976d2;
  margin: 16px 0;
  padding: 12px 16px;
  background-color: #f8f9fa;
  border-radius: 0 8px 8px 0;
}

.markdown-content :deep(hr) {
  border: none;
  height: 2px;
  background: linear-gradient(to right, #1976d2, #e3f2fd, #1976d2);
  margin: 32px 0;
  border-radius: 1px;
}

/* Custom scrollbar */
.markdown-content::-webkit-scrollbar {
  width: 8px;
}

.markdown-content::-webkit-scrollbar-track {
  background: rgba(var(--v-theme-surface-variant), 0.3);
  border-radius: 4px;
}

.markdown-content::-webkit-scrollbar-thumb {
  background: rgba(var(--v-theme-primary), 0.5);
  border-radius: 4px;
}

.markdown-content::-webkit-scrollbar-thumb:hover {
  background: rgba(var(--v-theme-primary), 0.7);
}

/* Mobile responsiveness */
@media (max-width: 960px) {
  .markdown-content {
    padding: 20px;
    font-size: 0.9rem;
    max-height: 75vh;
  }
  
  .markdown-content :deep(h1) {
    font-size: 1.8rem;
  }
  
  .markdown-content :deep(h2) {
    font-size: 1.4rem;
  }
  
  .markdown-content :deep(h3) {
    font-size: 1.2rem;
  }
}

@media (max-width: 600px) {
  .terms-of-service-view {
    padding: 12px 0;
  }
  
  .markdown-content {
    padding: 16px;
    font-size: 0.85rem;
    max-height: 70vh;
  }
  
  .markdown-content :deep(h1) {
    font-size: 1.6rem;
  }
  
  .markdown-content :deep(h2) {
    font-size: 1.3rem;
  }
  
  .markdown-content :deep(h3) {
    font-size: 1.1rem;
  }
}
</style>
